name: Gradle Release Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      # For stuff need our private packages
      # USERNAME: ${{ secrets.SERVICE_ID }}
      # TOKEN: ${{ secrets.SERVICE_PAT }}
      # For stuff that doesn't need our private packages
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github
          cache: 'gradle'
          settings-path: ${{ github.workspace }}
      - name: Gradle build
        run: gradle build
      - name: Gradle test
        run: gradle test
      - name: Publish to GitHub Packages
        run: gradle publish -PpublishZgpr=true
